name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"
jobs:
  build:
    # Changed @main to @v0.7.0 to fix the trait bound error
    uses: haobogu/rmk/.github/workflows/user_build.yml@v0.7.0
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
