name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"
jobs:
  build:
    # Use 'main' but we will rely on your Cargo.toml to fix the error
    uses: HaoboGu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      # If you deleted vial.json, remove the line below
      vial_json_path: "vial.json" 
