name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"
jobs:
  build:
    uses: HaoboGu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      # If you deleted vial.json, you MUST remove the line below
      vial_json_path: "vial.json"
